name: Auto AI Blogger Post (USA Time)

on:
  schedule:
    - cron: "0 13 * * *"   # 9 AM EST
    - cron: "0 19 * * *"   # 3 PM EST
    - cron: "0 1 * * *"    # 9 PM EST (আগামী দিনের 1 AM UTC)
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Run Blogger Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          BLOGGER_POST_EMAIL: ${{ secrets.BLOGGER_POST_EMAIL }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python ai_blogger_random_topics.py
