name: ai_blogger_email.py

on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 3 * * *"
    - cron: "0 4 * * *"
    - cron: "30 6 * * *"
    - cron: "0 10 * * *"
    - cron: "0 14 * * *"
    - cron: "0 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ai_blogger_email
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          BLOGGER_POST_EMAIL: ${{ secrets.BLOGGER_POST_EMAIL }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python ai_blogger_hf_email.py
